### ISSUE TITLE
Support .pem private key pattern

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/github-secret-scanner-skill#173]
We'd like an example configuration for blocking when someone checks in a private .pem file.

**Comment by neilprosser** [comment]
Here's the pattern I used (it's a Clojure pattern so might need a bit of tweaking)...

https://github.com/atomisthq/common-clj/blob/541894a51d7cacabf1c85483cf00de04d184c35a/src/atomist/logging/redaction.clj#L41
