### ISSUE TITLE
Ignore SHA integrity hashes from pnpm lock file

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/github-secret-scanner-skill#18]
The secret scanner seems to be flagging SHA integrity hashes from our pnpm lock file (e.g. https://github.com/crdschurch/group-leader/blob/7f8b406c5ad3491d8fdaae83fbf20f54ec7196f7/pnpm-lock.yaml#L51).

**Comment by cdupuis** [comment]
Please add this file to glob patterns as an exclusion:

`!pnpm-lock.yaml`
