### ISSUE TITLE
Need advice on avoiding scanner warnings

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/github-secret-scanner-skill#222]
Two regular expressions in codebase:

#"https://(.*:x-oauth-basic)@(.*)"
and
#"https://(atomist:.*)@(.*)"

are triggering, but they're hard to list as exceptions because they are themselves patterns.  Are there any options for case like this?

**Comment by cdupuis** [comment]
You could put the matched values in as exceptions. I think that should work.

**Comment by cdupuis** [comment]
I corrected the exclusions in the skill configuration.
