### ISSUE TITLE
Annotation links

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/github-secret-scanner-skill#223]
![Screen Shot 2021-05-20 at 12 54 40 PM](https://user-images.githubusercontent.com/1643888/119040714-9c9ae180-b96a-11eb-9310-720c5d57c7e7.png)

The "check failure on line 15 ... " links here are not linking to the right code.  Is that a known issue?

**Comment by cdupuis** [comment]
yeah, that happens with every annotation that is not in the changeset of the commit.
