### ISSUE TITLE
Seeing two checks from secret scanner

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/github-secret-scanner-skill#85]
![Screen Shot 2020-10-31 at 11 24 20 PM](https://user-images.githubusercontent.com/1643888/97796545-66656280-1bd0-11eb-8138-fbc288a04301.png)

Also, one of them has the title "Detected Secrets", which is somewhat confusing given that the next line is "No secrets detected"

![Screen Shot 2020-10-31 at 11 23 42 PM](https://user-images.githubusercontent.com/1643888/97796549-6ebd9d80-1bd0-11eb-95f2-e1ad20026b36.png)

**Comment by slimslenderslacks** [comment]
This is most likely a test org attached to two workspaces, where one has an old version of the skill.

**Comment by cdupuis** [comment]
One is from atomista app in staging.
